---
- name: Get checksum
  set_fact:
    blocky_checksum: "{{ lookup('url', blocky_checksum_url).split(',') |
        select('regex', regex) |
        first | split(' ') | first }}"
  run_once: true
  vars:
    regex: "{{ '^.* ' ~ __blocky_tar|trim }}"

- name: Download blocky
  get_url:
    url: "{{ blocky_url }}"
    dest: "/tmp/blocky-{{ blocky_version }}.tgz"
    checksum: "sha256:{{ blocky_checksum }}"

- name: Install blocky
  unarchive:
    src: "/tmp/blocky-{{ blocky_version }}.tgz"
    dest: /usr/local/bin
    remote_src: true
    include: blocky
    creates: /usr/local/bin/blocky
    owner: root
    group: root
    mode: 0755

- name: Create blocky directory
  file:
    path: /etc/blocky
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy blocky.service file
  template:
    src: blocky.service.j2
    dest: /etc/systemd/system/blocky.service
    owner: root
    group: root
    mode: 0644
  notify: restart blocky

- name: Copy configuration file
  template:
    src: config.yml.j2
    dest: /etc/blocky/config.yml
    owner: root
    group: root
    mode: 0644
  notify: restart blocky

- name: Start and enable blocky
  systemd:
    name: blocky
    state: started
    enabled: true
    daemon_reload: true

- wait_for:
    port: "{{ blocky_dns_port }}"
