github_access_token: ENC[AES256_GCM,data:MiCJT3AgzQwU4i+Clze/z7zF8nfICUh7BLhbL2EOOnqk7M8E3XtdTQ==,iv:FHbwgvPJpwsDQmvE5y9SPv3SdnBxnmM9tlzZNlg4NhE=,tag:znpw5rv9ICDUZs9xnwGiDw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xsm57ruhucfmyuxgg7yyyj70x27yvse5fdjacgnpyhxs3p40rvcseuy5yu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGb0hTaW9GcUM4aGRDZTNz
            aS9rMGpKLytXcVFNQjlIdEt5a0dEZnB2dGpVCmE3VDc4dytGUWZzVXJjcFNmMy90
            azRqKyt5ck9Ka1lYSXJKb0xXNW1VTkUKLS0tIHhHbURWM0dlSFphWU8rSFdKNGlK
            cjJmUkw0U0k2VzRlZExEK3B2MTYwWlEK/BJJ2aprs/r5fIAqveGWbAPz1IgbijMP
            eO/6hq/OgQf6ScMzIQlJ5QnMy11PaQ/kA/fGvtQ4k6mAUcgDsbKXIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-29T14:30:10Z"
    mac: ENC[AES256_GCM,data:l9Dvlid1y6qJ/ELqrvnoDls45cGTeYD443IMQPxRV7fyvPfWShoiw0dUol6L7NJ91B/Z2uyxVJh1YkebxZuF48P1P0r9h9lsyv11Lw1eNISUIqjSUWjdRK5eg+dQ4vRrUoTSfAshjgJ8UPX2EQT3RZBnNjOZEjnKc8mF1e02XrY=,iv:mDZ+T2SpOCqWggBVUq+hIT+6KlwvX7zqrfJW+GLG/0w=,tag:jbHLFYK/TZi78RXE4B2Rnw==,type:str]
    pgp: []
    encrypted_regex: .*(token).*
    version: 3.7.1
