---
- name: Install docker module
  pip:
    name: docker

- name: Create drone RPC secret
  set_fact:
    drone_rpc_secret: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=24') }}"

- name: Create drone directory
  become: true
  become_user: "{{ user }}"
  file:
    path: "{{ docker_destination }}/drone"
    state: directory

- name: Copy Drone compose template to remote (does not overwrite)
  become: true
  become_user: "{{ user }}"
  template:
    src: "{{ item.src }}"
    dest: "{{ docker_destination }}/drone/{{ item.path | regex_replace('\\.j2$', '') }}"
    backup: true
  with_filetree: "../templates/drone/"
  when: item.state == "file"
