- name: Create .ssh directory
  file:
    path: "{{ ssh_path }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: directory
    mode: 0700

- name: Add SSH config file
  copy:
    src: "../files/ssh_config"
    dest: "{{ ssh_path }}/config"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0600"
    backup: true

- name: Generate public-private keypair
  community.crypto.openssh_keypair:
    state: present
    type: ed25519
    owner: "{{ user }}"
    group: "{{ user }}"
    path: "{{ ssh_key_file }}"
