default_stages: [push, commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-added-large-files

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.13.0
    hooks:
      - id: gitleaks-docker

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.75.0
    hooks:
      - id: terraform_fmt
        args:
          - --args=-diff
          - --args=-recursive
      - id: terraform_validate

  # - repo: https://github.com/ansible-community/ansible-lint
  #   rev: v6.6.1
  #   hooks:
  #     - id: ansible-lint
  #       entry: ansible-lint --project-dir ./ansible -c ./ansible/.ansible-lint ./ansible
  #       pass_filenames: false
