---
site_name: Homelab
repo_name: kencx/homelab
repo_url: https://github.com/kencx/homelab

theme:
  name: material
  features:
    - navigation.indexes
    # - navigation.expand
    - search.highlight
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: false
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Prerequisites: prerequisites.md
  - Getting Started: 'getting_started.md'
  - Provisioning:
      # - Overview: 'provisioning.md'
      - Images:
          - Cloud Images: 'images/cloud_image.md'
          - Packer: 'images/packer.md'
      - Terraform:
          - Postgres: 'terraform/postgres.md'
  - Ansible Roles:
      - Arch Repository: 'roles/arch_repository.md'
      - Autorestic: 'roles/autorestic.md'
      - Blocky: 'roles/blocky.md'
      - Common: 'roles/common.md'
      - Consul: 'roles/consul.md'
      - Consul Template: 'roles/consul-template.md'
      - Coredns: 'roles/coredns.md'
      - Issue Cert: 'roles/issue_cert.md'
      - NFS: 'roles/nfs.md'
      - Nomad: 'roles/nomad.md'
      - Unseal Vault: 'roles/unseal_vault.md'
      - Vault: 'roles/vault.md'
  - Backups: backups.md
  - Apps:
      - index: 'apps/index.md'
      - Actual: 'apps/actual.md'
      - Calibre Web: 'apps/calibre_web.md'
      - Gotify: 'apps/gotify.md'
      - Diun: 'apps/diun.md'
      - Linkding: 'apps/linkding.md'
      - Traefik: 'apps/traefik.md'
      - yarr: 'apps/yarr.md'
  - References:
      - Known Issues: 'references/issues.md'
      - Work Log: 'references/LOG.md'
      - Roadmap: 'references/TODO.md'
