---
- hosts: pve
  any_errors_fatal: true
  gather_facts: false
  tags: create
  vars_files:
    - vars.yml
  roles:
    - name: Create temp LXC
      role: create_lxc

- hosts: template
  any_errors_fatal: true
  gather_facts: false
  tags: bootstrap
  vars_files:
    - vars.yml
  pre_tasks:
    - name: Wait for connection
      wait_for_connection:
        delay: 5
        timeout: 300
    - name: Gather facts
      setup:

  roles:
    - name: Bootstrap LXC
      role: bootstrap
      when: not ansible_check_mode

- hosts: pve
  any_errors_fatal: true
  gather_facts: false
  tags: destroy
  vars_files:
    - vars.yml
  roles:
    - name: Template temp LXC
      role: template_lxc
      vars:
        date: "{{ lookup('pipe', 'date +%Y%m%d') }}"
