user:
  debian:
    exists: true
    groups:
      - debian
      - sudo
      - docker
    home: /home/debian

file:
  /mnt/storage:
    exists: true
    mode: "0755"
    owner: debian
    group: debian
    filetype: directory

package:
  nomad:
    installed: true
  consul:
    installed: true
  vault:
    installed: true
  nfs-common:
    installed: true
  jq:
    installed: true
  unzip:
    installed: true

gossfile:
  docker.yml: {}
  security.yml: {}
