all:
  children:
    template:
      hosts:
        10.10.10.254:
      vars:
        ansible_user: root
        ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
        ansible_ssh_private_key_file: /tmp/temp_ssh_key

    pve:
      hosts:
        pve.kencv.xyz:
      vars:
        ansible_user: ansible
        ansible_ssh_private_key_file: ~/.ssh/id_ed25519
        ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
        proxmox_api_token_id: ""
        proxmox_api_token_secret: ""

    cmd:
      hosts:
        cmd.kencv.xyz:
        cmd-drone.kencv.xyz:
    dev:
      hosts:
        dev.kencv.xyz:
    prod:
      hosts:
        prod.kencv.xyz:

    lxc:
      children:
        cmd:
        dev:
        prod:
      vars:
        ansible_user: debian
        ansible_ssh_private_key_file: ~/.ssh/pve
