---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
  default_box: "debian/bullseye64"
platforms:
  - name: instance
    box: "debian/bullseye64"
    config_options:
      synced_folder: false

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../roles"
    ANSIBLE_STDOUT_CALLBACK: yaml
verifier:
  name: ansible
