---
blocky_version: 0.21
blocky_arch_map:
  armv7l: armv7
  x86_64: x86_64
blocky_arch: "{{ blocky_arch_map[ansible_architecture] }}"
blocky_tar: blocky_v{{ blocky_version }}_{{ ansible_system }}_{{ blocky_arch }}.tar.gz

blocky_dns_port: 53
blocky_user: blocky
blocky_group: blocky

blocky_client_lookup: {}
