---
- name: Create Consul directories
  file:
    path: "{{ item }}"
    mode: 0755
    owner: consul
    group: consul
    state: directory
  with_items:
    - "{{ consul_config_dir }}"
    - "{{ consul_data_dir }}"

- name: Create Consul TLS directory
  file:
    path: "{{ consul_tls_dir }}"
    mode: 0700
    owner: consul
    group: consul
    state: directory

- name: Setup Consul Gossip Encryption
  become: true
  import_tasks: gossip.yml

- name: Setup Consul TLS
  become: true
  import_tasks: tls.yml

- name: Copy service file
  become: true
  template:
    src: "consul.service.j2"
    dest: "/etc/systemd/system/consul.service"
    mode: 0644
    owner: root
    group: root
  notify: restart consul

- name: Copy watches script
  become: true
  template:
    src: "healthcheck.sh.j2"
    dest: "{{ consul_data_dir }}/healthcheck.sh"
    mode: 0755
    owner: consul
    group: consul
  when:
    - "'server' in group_names"
    - setup_consul_watches

- name: Copy Consul config files
  block:
    - name: Common config
      template:
        src: "consul.hcl.j2"
        dest: "{{ consul_config_dir }}/consul.hcl"
        mode: 0644
        owner: consul
        group: consul

    - name: Server-only config
      template:
        src: "server.hcl.j2"
        dest: "{{ consul_config_dir }}/server.hcl"
        mode: 0644
        owner: consul
        group: consul
      when: "'server' in group_names"

    - name: Client-only config
      template:
        src: "client.hcl.j2"
        dest: "{{ consul_config_dir }}/client.hcl"
        mode: 0644
        owner: consul
        group: consul
      when: "'server' not in group_names"
  notify:
    - reload consul

- name: Start Consul
  become: true
  systemd:
    name: consul
    state: started
    enabled: true
    daemon_reload: true
  register: consul_started

# Apply all service and config changes
- name: Run handlers now
  meta: flush_handlers

- name: Wait for Consul port
  wait_for:
    port: 8501
    state: started
