---
- name: Add TLS template stanza to consul-template
  blockinfile:
    path: "{{ consul_template_config }}"
    marker: "# {mark} Consul TLS"
    backup: true
    validate: consul-template -config=%s -parse-only
    block: |
      template {
        contents = <<EOF
      {{ '{{' }} with secret "pki_int/issue/cluster" "common_name=server.dc1.consul" "ttl=24h" "alt_names=localhost" "ip_sans={{ consul_ip_sans }}" {{ '}}' }}
      {{ '{{' }} .Data.certificate {{ '}}' }}
      {{ '{{' }} end {{ '}}' }}
      EOF
        destination = "{{ consul_tls_dir }}/cert.crt"
        perms = 0600
        user = "consul"
        group = "consul"
        command = "date && if systemctl is-active consul; then service consul reload; fi"
      }

      template {
        contents = <<EOF
      {{ '{{' }} with secret "pki_int/issue/cluster" "common_name=server.dc1.consul" "ttl=24h" "alt_names=localhost" "ip_sans={{ consul_ip_sans }}" {{ '}}' }}
      {{ '{{' }} .Data.private_key {{ '}}' }}
      {{ '{{' }} end {{ '}}' }}
      EOF
        destination = "{{ consul_tls_dir }}/key.pem"
        perms = 0400
        user = "consul"
        group = "consul"
        command = "date && if systemctl is-active consul; then service consul reload; fi"
      }

      template {
        contents = <<EOF
      {% raw %}{{ with secret "pki_int/issue/cluster" "common_name=server.dc1.consul" "ttl=24h" }}
      {{ .Data.issuing_ca }}
      {{ end }}
      {% endraw %}
      EOF
        destination = "{{ consul_tls_dir }}/ca.crt"
        perms = 0600
        user = "consul"
        group = "consul"
        command = "date && if systemctl is-active consul; then service consul reload; fi"
      }
  notify: reload consul-template
