---
proxmox_node: "pve"
proxmox_api_host: "pve"
proxmox_api_user: "ansible@pam"
proxmox_api_password: ""
proxmox_api_token_id: ""
proxmox_api_token_secret: ""
proxmox_storage: "volumes"

base_image: "debian-11-standard_11.3-1_amd64.tar.zst"
temp_vmid: 900
temp_hostname: "lxc-template"
temp_disk_size: "volumes:5"
temp_ip_address: "10.10.10.254/24"
temp_gateway: "10.10.10.1"
