---
- hosts: cmd
  tags: cmd
  vars_files:
    - vars.yml
  roles:
    - role: kencx.ansible.terraform
    - role: kencx.ansible.ansible
    - role: kencx.ansible.nfs
      vars:
        - nfs_server_src_dir: "{{ cmd_nfs_share }}"

  tasks:
    - import_tasks: tasks/ssh_config.yml
    - import_tasks: tasks/setup_docker.yml
      become: true

    - name: Install pre-commit
      become: true
      become_user: "{{ user }}"
      community.general.pipx:
        name: pre-commit
        install_deps: true
        state: present

- hosts: drone
  tags: drone
  vars_files:
    - vars.yml
  roles:
    - role: kencx.ansible.nfs
      vars:
        - nfs_server_src_dir: "{{ drone_nfs_share }}"

  tasks:
    - import_tasks: tasks/setup_drone.yml

- import_playbook: tests/smoke_test.yml
