---
- hosts: cmd # , drone
  vars_files:
    - vars.yml
  tasks:
    - import_tasks: tasks/ssh_config.yml

- hosts: cmd
  become: true
  vars_files:
    - vars.yml
  roles:
    - role: kencx.ansible.terraform
      vars:
        - latest_terraform_version: 1.1.9
    - role: kencx.ansible.ansible

  tasks:
    - name: Install pre-commit
      become_user: "{{ user }}"
      community.general.pipx:
        name: pre-commit
        install_deps: true
        state: present

    - import_tasks: tasks/setup_docker.yml

- hosts: drone
  become: true
  vars_files:
    - vars.yml
  tasks:
    - import_tasks: tasks/setup_drone.yml

# smoke tests
- import_playbook: tests/smoke_test.yml
