
# nfs mount
cmd_nfs_share: "/home/debian/apps/cmd-apps"
drone_nfs_share: "/home/debian/apps/drone"
nfs_mnt_path: "/mnt/docker"

user: debian
latest_terraform_version: 1.1.9

# ssh
ssh_path: "/home/{{ user }}/.ssh"
ssh_key_file: "{{ ssh_path }}/github"

# docker
domain_name: "cmd.kencv.xyz"
proxy_network: "proxy"
socket_proxy_network: "socket-proxy"
docker_destination: "{{ nfs_mnt_path }}"

## docker containers

# traefik
traefik_img_version: "v2.6.1"
traefik_port: 8085

# portainer
portainer_img_version: "2.11.1"
portainer_data_dir: "./data"
portainer_port: 9000

# gitea
gitea_img_version: "1.16"
gitea_data_dir: "./gitea"
gitea_port: 3000

# drone
drone_img_version: "2.11.1"
drone_data_dir: "./drone"
drone_port: 8000
drone_ip: "10.10.10.106"
drone_url: "http://{{ drone_ip }}:{{ drone_port }}"
