---
# consul-template requires write access to all template destination directories.
# - name: Create consul-template user
#   user:
#     name: consul-template
#     groups: ["vault", "consul", "nomad"]
#     append: true
#     create_home: false
#     state: present

- name: Create consul-template directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: root
    group: root
  with_items:
    - "{{ consul_template_config_dir }}"

- name: Copy consul-template service file
  template:
    src: "consul-template.service"
    dest: "/etc/systemd/system/consul-template.service"
    mode: 0644
    owner: root
    group: root
  notify: reload consul-template

- name: Copy consul-template config
  template:
    src: "consul-template.hcl.j2"
    dest: "{{ consul_template_config_dir }}/consul-template.hcl"
    mode: 0640
    owner: root
    group: root
  notify: reload consul-template

- name: Start consul-template
  systemd:
    name: consul-template
    state: started
    enabled: true
    daemon_reload: true
