- name: Clone bare Git repo
  git:
    repo: "{{ repo_url }}"
    dest: "{{ repo_dest }}"
    bare: true
    clone: true

- name: Prepare sparse checkout
  shell: |
    git sparse-checkout init
    git sparse-checkout set {{ item }}
  with_items:
    - "dots/nvim" # change to list variable

- name: Checkout sparse repo
  shell: |
    git checkout master
