---
- name: Create repository directory
  file:
    path: "{{ arch_repository_dir }}"
    owner: "{{ arch_repository_user }}"
    group: "{{ arch_repository_user }}"
    mode: 0755
    state: directory

- name: Check repository database present
  stat:
    path: "{{ arch_repository_dir }}/{{ arch_repository_name }}.db.tar.xz"
  register: arch_repo_db

- name: Create repository database
  command: repo-add {{ arch_repository_dir }}/{{ arch_repository_name }}.db.tar.xz
  when:
    - arch_repo_db.stat.exists is defined
    - not arch_repo_db.stat.exists

- name: Set repository contents' ownership to {{ arch_repository_user }}
  file:
    path: "{{ arch_repository_dir }}"
    owner: "{{ arch_repository_user }}"
    group: "{{ arch_repository_user }}"
    mode: u=rwX,g=rX,o=rX
    recurse: true

- name: Add repository to pacman.conf
  block:
    - template:
        src: "arch_repo.j2"
        dest: "/etc/pacman.d/{{ arch_repository_name }}"
        owner: root
        group: root
        mode: 0644

    - lineinfile:
        path: /etc/pacman.conf
        line: "Include = /etc/pacman.d/{{ arch_repository_name }}"
        state: present
        owner: root
        group: root
        mode: 0644
