---
- hosts: cmd
  vars_files:
    - vars.yml
  roles:
    - name: Install terraform
      role: kencx.ansible.terraform
      vars:
        - latest_terraform_version: 1.1.9

    - name: Install ansible with pipx
      role: kencx.ansible.ansible

    - name: Create github SSH key
      role: ssh_config
      vars:
        - ssh_key_name: "github"

    - name: Mount NFS share
      role: kencx.ansible.nfs

      # does not start containers
    - name: Set up docker infrastructure
      role: docker_setup
      vars:
        - docker_source_method: "skip"

  tasks:
    - name: Install pre-commit
      become: true
      become_user: "{{ user }}"
      community.general.pipx:
        name: pre-commit
        install_deps: true
        state: present

- import_playbook: tests/smoke_test.yml
