---
- hosts: cmd # , drone
  vars_files:
    - vars.yml
  tasks:
    - import_tasks: tasks/ssh_config.yml

- hosts: cmd
  become: true
  vars_files:
    - vars.yml
  roles:
    - role: kencx.ansible.terraform
      vars:
        - latest_terraform_version: 1.1.9
  tasks:
    - import_tasks: tasks/install_ansible.yml
    - import_tasks: tasks/setup_docker.yml
    - import_tasks: tasks/start_docker.yml
      when: first_time_setup == false

- hosts: drone
  become: true
  vars_files:
    - vars.yml
  tasks:
    - import_tasks: tasks/setup_drone.yml

# smoke tests
- import_playbook: tests/smoke_test.yml
