---
common_user: debian
common_timezone: "Asia/Singapore"
common_keyring_dir: "/etc/apt/keyrings"
common_nfs_dir: "/mnt/storage"
common_packages:
  - sudo
  - curl
  - git
  - openssh-server
  - vim
  - make
  - gnupg
  - nfs-common
  - software-properties-common
  - jq
  - unzip
  - ca-certificates
  - qemu-guest-agent
common_dotfiles_url: ""

common_nomad_version: "1.5.2-1"
common_consul_version: "1.15.1-1"
common_vault_version: "1.13.0-1"
common_consul_template_version: "0.30.0-1"
common_reset_nomad: true
