---
common_user: debian
common_keyring_dir: "/etc/apt/keyrings"
common_nfs_dir: "/mnt/storage"
common_packages:
  - sudo
  - curl
  - git
  - openssh-server
  - vim
  - make
  - gnupg
  - nfs-common
  - software-properties-common
  - jq
  - unzip
  - ca-certificates
