---
- name: Verify
  hosts: cmd
  gather_facts: false
  become_user: debian
  tasks:
    - name: User debian is present
      user:
        name: debian
        state: present

    - name: SSH directory is present
      file:
        path: /home/debian/.ssh/
        state: directory
        owner: debian
        group: debian
        mode: 0700

    - name: SSH config is present
      file:
        path: /home/debian/.ssh/config
        state: file
        owner: debian
        group: debian
        mode: 0600

    - name: Github SSH key is present
      file:
        path: "/home/debian/.ssh/{{ item.file }}"
        state: file
        owner: debian
        group: debian
        mode: "{{ item.mode }}"
      loop:
        - { file: github.pub, mode: "0644" }
        - { file: github, mode: "0600" }

    # - name: Github SSH connection is successful

    # - name: Ansible is installed
    # - name: ansible-lint is installed
    # - name: Terraform is installed
