---
certbot_dir: "/etc/letsencrypt"
certbot_webroot: "/var/www/letsencrypt"
certbot_admin_email: "foo@example.com"

certbot_certs: []
  # - email: foo@example.com
  #   webroot: /var/www/letsencrypt
  #   domains:
  #     - foo.example.com
  # - domains:
  #     - foo.example1.com

certbot_create_command: >-
  certbot certonly
  --non-interactive --agree-tos
  --email {{ item.email | default(certbot_admin_email) }}
  --webroot
  --webroot-path {{ item.webroot | default(certbot_webroot) }}
  -d {{ item.domains | join(',') }}
