---
nas_user: "debian"
nas_backup_partition: ""
nas_backup_mount_dir: ""
nas_backup_restore_dir: "/home/{{ nas_user }}/restore-test"
nas_backup_export_dir: "/home/{{ nas_user }}/node_exporter"
nas_backup_export_file: "{{ nas_backup_export_dir }}/restic.prom"
nas_backup_time: "06:00:00"

restic_version: "0.15.2"
autorestic_version: "1.7.7"
autorestic_bin_dir: "/usr/local/bin"
autorestic_config_dir: "/root"
autorestic_log_dir: "/var/log/autorestic"
autorestic_log_file: "{{ autorestic_log_dir }}/autorestic.log"

autorestic_locations: []
autorestic_backends: []
autorestic_forget: {}
