---
- hosts: template
  become: true
  vars:
    - user: debian
  pre_tasks:
    - name: Update apt packages
      apt:
        update_cache: true
        cache_valid_time: 86400
        upgrade: true

    - name: Wait for dpkg lock to be released
      shell: while lsof /var/lib/dpkg/lock-frontend ; do sleep 10 ; done;
      changed_when: false

    - name: Update and install packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - sudo
        - curl
        - git
        - openssh-server
        - vim
        - make
        - gnupg
        - nfs-common
        - software-properties-common
      register: apt_action
      retries: 10
      until: apt_action is success or ('/var/lib/dpkg/lock-frontend' not in apt_action.msg)

  roles:
    - name: Install docker
      role: geerlingguy.docker
      vars:
        # install docker compose plugin instead of docker-compose binary
        - docker_install_compose_plugin: true
        - docker_install_compose: false
        - docker_users: ["{{ user }}"]

    - name: Security hardening
      role: kencx.ansible.security
      vars:
        - ssh_disable_root_login: true

    - name: Install goss
      role: ../roles/goss

  tasks:
    - name: Add Hashicorp apt repository
      block:
        - name: Add Hashicorp APT repository key
          apt_key:
            url: https://apt.releases.hashicorp.com/gpg
            state: present

        - name: Add Hashicorp APT repository
          apt_repository:
            repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
            state: present

    - name: Install Hashicorp tools
      apt:
        name: "{{ item }}"
        state: present
        update_cache: true
        cache_valid_time: 86400
      with_items:
        - nomad
        - consul
        - vault

    - name: Create NFS share directories
      file:
        path: "/mnt/storage"
        mode: 0755
        owner: "{{ user }}"
        group: "{{ user }}"
        state: directory

    - name: Goss smoke test
      import_role:
        name: ../roles/goss
      vars:
        - goss_file_template: "./templates/goss/base.yml.j2"
