---
- hosts: client
  become: true
  vars:
    - server_ip: "10.10.10.110"
    - nfs_ip: "10.10.10.102"
    - nfs_share_mounts:
        - src: "{{ nfs_ip }}:/home/debian/apps/test-apps"
          path: "/mnt/storage"
          state: mounted

  tasks:
    - name: Copy config files
      become: true
      template:
        src: "./templates/client/{{ item }}.hcl.j2"
        dest: "/etc/{{ item }}.d/{{ item }}.hcl"
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: 0644
      vars:
        - nomad_server_ip: "{{ server_ip }}"
        - consul_server_ip: "{{ server_ip }}"
      with_items:
        - nomad
        - consul
      notify:
        - reload nomad
        - reload consul

    - name: Start nomad
      become: true
      systemd:
        name: nomad
        state: started
        enabled: true
        daemon_reload: true
      register: nomad_started

    - name: Start consul
      become: true
      systemd:
        name: consul
        state: started
        enabled: true
        daemon_reload: true
      register: consul_started

    - name: Mount NFS shares
      become: true
      import_role:
        name: kencx.ansible.nfs

    - name: Goss smoke test
      import_role:
        name: kencx.ansible.goss
      vars:
        - goss_dir: "./templates/goss"
        - goss_file: "client.yml"

  handlers:
    - name: reload nomad
      systemd:
        name: nomad
        state: reloaded
      when: not nomad_started.changed

    - name: reload consul
      systemd:
        name: consul
        state: reloaded
      when: not consul_started.changed
