---
- hosts: template
  become: true
  tasks:
    - name: Create Nomad directories
      become: true
      file:
        path: "{{ item }}"
        mode: 0755
        owner: nomad
        group: nomad
        state: directory
      with_items:
        - "/opt/nomad/data"
        - "/etc/nomad.d"

    - name: Create Consul directories
      become: true
      file:
        path: "{{ item }}"
        mode: 0755
        owner: consul
        group: consul
        state: directory
      with_items:
        - "/opt/consul"
        - "/etc/consul.d"

    - name: Install CNI plugins
      block:
        - name: Create directory
          file:
            path: "/opt/cni/bin"
            mode: 0775
            owner: root
            group: root
            state: directory

        - name: CNI bridge plugin exists
          stat:
            path: "/opt/cni/bin/bridge"
          register: cni_bridge

        - name: Unarchive CNI plugins
          unarchive:
            src: "https://github.com/containernetworking/plugins/releases/download/v1.1.1/cni-plugins-linux-amd64-v1.1.1.tgz"
            dest: "/opt/cni/bin"
            remote_src: true
          when: not cni_bridge.stat.exists

    - name: Copy service file
      become: true
      copy:
        src: "./templates/client/{{ item }}"
        dest: "/etc/systemd/system/{{ item }}"
        owner: root
        group: root
        mode: "0644"
      with_items:
        - "nomad.service"
        - "consul.service"
