---
# This playbook sets up consul-template for Nomad and Consul
# TLS certificates and certificate rotation.
# It can be ran on both server and client nodes with the
# appropriate Vault address.
- hosts: all
  become: true
  vars:
    consul_data_dir: "/opt/consul"
    consul_template_dir: "{{ consul_data_dir }}/templates"
    consul_tls_dir: "{{ consul_data_dir }}/tls"

    nomad_data_dir: "/opt/nomad/data"
    nomad_tls_dir: "{{ nomad_data_dir }}/tls"

    vault_tls_dir: "/opt/vault/tls"
    vault_certificate_dir: "/usr/share/ca-certificates/vault"

  tasks:
    # Ensure Vault root and intermediate CA are initialized and configured

    # - name: Install consul-template
    #   unarchive:
    #     src: "https://releases.hashicorp.com/consul-template/0.29.2/consul-template_0.29.2_linux_amd64.zip"
    #     dest: "/usr/bin"
    #     remote_src: true

    # TODO insecure
    - name: Read token
      command: cat /root/.vault-root-token
      register: vault_token_raw
      no_log: true

    - set_fact:
        vault_token: "{{ vault_token_raw.stdout }}"
      no_log: true

    - name: Create consul-template directory
      file:
        path: "{{ consul_template_dir }}"
        state: directory

    - name: Copy consul-template service file
      copy:
        src: "./templates/consul-template/consul-template.service"
        dest: "/etc/systemd/system/consul_template.service"
        mode: 0644
        owner: root
        group: root
      notify:
        - reload consul_template

    - name: Copy consul-template config
      template:
        src: "./templates/consul-template/consul-template.hcl.j2"
        dest: "{{ consul_template_dir }}/consul_template.hcl"
        mode: 0600
        owner: consul
        group: consul
      notify:
        - reload consul_template

    - name: Create TLS directories
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ consul_tls_dir }}"
        - "{{ nomad_tls_dir }}"

    - name: Start consul-template
      systemd:
        name: consul_template
        state: started
        enabled: true
      register: consul_template_started

  handlers:
    - name: reload consul_template
      systemd:
        name: consul_template
        state: reloaded
      when: not consul_template_started.changed
