---
- hosts: "{{ host | default(omit) }}"
  become: true
  vars:
    nomad_config_dir: "/etc/nomad.d"
    nomad_data_dir: "/opt/nomad/data"
    consul_config_dir: "/etc/consul.d"
    consul_data_dir: "/opt/consul"
    reset_cluster_data: false

  tasks:
    - name: Create Nomad directories
      file:
        path: "{{ item }}"
        mode: 0755
        owner: nomad
        group: nomad
        state: directory
      with_items:
        - "{{ nomad_config_dir }}"
        - "{{ nomad_data_dir }}"

    - name: Create Consul directories
      file:
        path: "{{ item }}"
        mode: 0755
        owner: consul
        group: consul
        state: directory
      with_items:
        - "{{ consul_config_dir }}"
        - "{{ consul_data_dir }}"

    - name: Copy service file
      copy:
        src: "./templates/server/{{ item }}"
        dest: "/etc/systemd/system/{{ item }}"
        owner: root
        group: root
        mode: "0644"
      with_items:
        - "nomad.service"
        - "consul.service"
      notify:
        - reload nomad
        - reload consul

    - name: Copy Nomad config files
      template:
        src: "./templates/server/nomad.hcl.j2"
        dest: "{{ nomad_config_dir }}/nomad.hcl"
        owner: nomad
        group: nomad
        mode: 0644
      vars:
        - bootstrap_expect: 1
      notify:
        - reload nomad

    - name: Copy Consul config files
      template:
        src: "./templates/server/consul.hcl.j2"
        dest: "{{ consul_config_dir }}/consul.hcl"
        owner: consul
        group: consul
        mode: 0644
      notify:
        - reload consul

    - name: Start Nomad
      systemd:
        name: nomad
        state: started
        enabled: true
        daemon_reload: true
      register: nomad_started

    - name: Start Consul
      systemd:
        name: consul
        state: started
        enabled: true
        daemon_reload: true
      register: consul_started

    # Apply all service and config changes
    - name: Run handlers now
      meta: flush_handlers

    - name: Wait for Nomad port
      wait_for:
        port: 4646
        state: started

    - name: Goss smoke test
      import_role:
        name: kencx.ansible.goss
      vars:
        - goss_dir: "./templates/goss"
        - goss_file: "server.yml"

    # WARNING! This clears all cluster node data.
    # This is only necessary when templating the server with Packer
    # Do not run this with Terraform
    - name: Reset cluster
      when: reset_cluster_data|bool
      block:
        - name: Stop Nomad, Consul
          systemd:
            name: "{{ item }}"
            state: stopped
            enabled: true
          with_items:
            - nomad
            - consul

        - name: Delete Nomad, Consul data directories
          file:
            path: "{{ item }}"
            state: absent
          with_items:
            - "{{ nomad_data_dir }}"
            - "{{ consul_data_dir }}"

        - name: Create Nomad directories
          file:
            path: "{{ nomad_data_dir }}"
            mode: 0755
            owner: nomad
            group: nomad
            state: directory

        - name: Create Consul directories
          file:
            path: "{{ consul_data_dir }}"
            mode: 0755
            owner: consul
            group: consul
            state: directory

  handlers:
    - name: reload nomad
      systemd:
        name: nomad
        state: reloaded
      when: not nomad_started.changed

    - name: reload consul
      systemd:
        name: consul
        state: reloaded
      when: not consul_started.changed
