---
- name: Ensure mandatory variables are set
  assert:
    that:
      - server_name is defined
      - proxy_pass is defined

- name: Install docker and docker-compose pip
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - docker
    - docker-compose

- name: Create sxkcd directories
  file:
    path: "{{ item }}"
    mode: 0775
    owner: "{{ sxkcd_user }}"
    group: "{{ sxkcd_user }}"
    state: directory
  with_items:
    - /home/{{ sxkcd_user }}/sxkcd
    - /home/{{ sxkcd_user }}/sxkcd/data
    - /home/{{ sxkcd_user }}/sxkcd/redis

- name: Copy sxkcd nginx config
  template:
    src: "./sxkcd.conf"
    dest: "{{ nginx_dir }}/conf.d/sxkcd.conf"
    owner: root
    group: root
    mode: 0644

# - name: Download xkcd comics
# ["./sxkcd", "download", "-f", "/data/comics.json"]

- name: Copy docker-compose.yml
  template:
    src: "docker-compose.sxkcd.yml.j2"
    dest: "/home/{{ sxkcd_user }}/sxkcd/docker-compose.yml"
    owner: "{{ sxkcd_user }}"
    group: "{{ sxkcd_user }}"
    mode: 0644

- name: Start sxkcd and redis
  docker_compose:
    project_src: "/home/{{ sxkcd_user }}/sxkcd"
    pull: true
    recreate: smart
    state: present

- name: Reload nginx
  systemd:
    name: nginx
    state: reloaded
