---
vault_config_dir: "/etc/vault.d"
vault_data_dir: "/opt/vault/data"
vault_log_dir: "/opt/vault/logs"
vault_tls_dir: "/opt/vault/tls"
vault_ca_cert_dir: "/usr/share/ca-certificates/vault"
vault_log_file: "{{ vault_log_dir }}/vault.log"

vault_store_bw: false
vault_unseal_key_file: "{{ vault_data_dir }}/.unseal_key"
vault_root_token_file: "{{ vault_data_dir }}/.root_token"

vault_terraform_workspace: "default"
vault_admin_password: "password"

vault_setup_agent: true
vault_server_fqdn: "{{ ansible_default_ipv4.address }}"
