---
nomad_config_dir: "/etc/nomad.d"
nomad_data_dir: "/opt/nomad/data"
nomad_tls_dir: "{{ nomad_data_dir }}/tls"
consul_template_config: "/opt/consul-template/consul_template.hcl"

# server
nomad_bootstrap_expect: 1

# client
nomad_server_ip: ""

nomad_common_name: "server.global.nomad"
nomad_ip_sans: "127.0.0.1"
