---
nomad_config_dir: "/etc/nomad.d"
nomad_data_dir: "/opt/nomad/data"
nomad_tls_dir: "{{ nomad_data_dir }}/tls"
consul_template_config: "/opt/consul-template/consul_template.hcl"

# vault
setup_vault_integration: true
vault_policy_dir: "/etc/vault.d/policies"

# server
nomad_bootstrap_expect: 1

# client
nomad_server_ip: ""

# certificate generation
nomad_vault_addr: "https://localhost:8200"
nomad_common_name: "server.global.nomad"
nomad_ip_sans: "127.0.0.1"
