---
# bootstrap_lxc
template_user: "debian"
template_password: "password"  # temp password to be changed on first login
template_uid: 1000

apps:
  - sudo
  - curl
  - vim
  - openssh-server
  - git
  - make

git_email: ""
git_user: ""
ssh_key_file: "/home/kenc/.ssh/pve.pub" # TODO remove dependence on kenc

# template_lxc
proxmox_node: "pve"
proxmox_api_host: "pve"
proxmox_api_user: "ansible@pam"

container_storage: "volumes"
temp_dir: "/tmp/debian-tmp/"
dump_dir: "/var/lib/vz/template/cache/"

template_name: "debian-11-docker"
