---
- hosts: all
  tasks:
  - name: Create container from base template
    proxmox:
      node: "{{ proxmox_node }}"
      api_host: "{{ proxmox_api_host }}"
      api_user: "{{ proxmox_api_user }}"
      api_token_id: "{{ proxmox_api_token_id }}"
      api_token_secret: "{{ proxmox_api_token_secret }}"
      vmid: "{{ template_id }}"

      hostname: "{{ template_hostname }}"
      password: "{{ template_root_password }}"
      ostemplate: "{{ base_template_path }}"
      storage: "{{ container_storage }}"
      netif: "{'net0':'name=eth0,gw={{ gateway }},ip={{ ip_address }},bridge=vmbr0'}"
      features:
        - nesting=1
      #   - keyctl=1

      unprivileged: yes
      onboot: no
      state: present

  - name: Start container
    proxmox:
      node: "{{ proxmox_node }}"
      api_host: "{{ proxmox_api_host }}"
      api_user: "{{ proxmox_api_user }}"
      api_token_id: "{{ proxmox_api_token_id }}"
      api_token_secret: "{{ proxmox_api_token_secret }}"

      vmid: "{{ template_id }}"
      state: started

