---
- name: restart nomad
  systemd:
    name: nomad
    state: restarted
  when: not nomad_started.changed

- name: reload nomad
  systemd:
    name: nomad
    state: reloaded
  when: not nomad_started.changed

- name: reload consul-template
  systemd:
    name: consul-template
    state: reloaded
