---
- name: Read consul-template policy
  copy:
    src: "consul_template_policy.hcl"
    dest: "{{ vault_config_dir }}/consul_template_policy.hcl"

- name: Create consul-template policy
  command: "vault policy write consul_template {{ vault_config_dir }}/consul_template_policy.hcl"
  register: create_ct_policy
  failed_when: create_ct_policy.rc != 0

- name: Setup consul-template authentication
  script: "../files/consul_template_auth_role.sh"
