---
# A single unseal key is sufficient for our purposes
- name: Initialize Vault
  command: vault operator init -key-shares=1 -key-threshold=1 -format=json
  no_log: true
  register: vault_init_raw

- set_fact:
    vault_init_json: "{{ vault_init_raw.stdout | from_json }}"
  no_log: true
  when: vault_init_raw is defined and vault_init_raw.stdout is defined

# The initialization of Vault outputs the root token and unseal key(s). We can choose to
# store these on the filesystem at the set paths or in Bitwarden. If stored on the
# filesystem, root is required for read access to both files. This is only recommended
# for testing and development purposes. If stored on Bitwarden, the bw_password variable
# must be defined and will be used to login to your Bitwarden account.

- name: Store unseal keys on filesystem
  copy:
    content: "{{ vault_init_json.unseal_keys_hex[0] }}"
    dest: "{{ vault_unseal_key_file }}"
    owner: root
    group: root
    mode: 0400
  no_log: true
  when:
    - vault_store_bw == false
    - vault_init_json is defined
    - vault_init_json.unseal_keys_hex is defined

- name: Store unseal keys in Bitwarden
  script: "bw_store.sh 'Vault Unseal Key' {{ vault_init_json.unseal_keys_hex[0] }} {{ bw_password }}"
  when:
    - vault_store_bw == true
    - vault_init_json is defined
    - vault_init_json.unseal_keys_hex is defined
  no_log: true
  register: bw_vault_unseal_key
  failed_when: bw_vault_unseal_key.stdout == "bw get failed"

# - debug:
#     var: bw_vault_unseal_key.stdout

- name: Store root token on filesystem
  copy:
    content: "{{ vault_init_json.root_token }}"
    dest: "{{ vault_root_token_file }}"
    owner: root
    group: root
    mode: 0400
  no_log: true
  when:
    - vault_store_bw == false
    - vault_init_json is defined
    - vault_init_json.root_token is defined

- name: Store root token in Bitwarden
  script: "bw_store.sh 'Vault Root Token' {{ vault_init_json.root_token }} {{ bw_password }}"
  when:
    - vault_store_bw == true
    - vault_init_json is defined
    - vault_init_json.root_token is defined
  no_log: true
  register: bw_vault_root_token
  failed_when: bw_vault_root_token.stdout == "bw get failed"

# - debug:
#     var: bw_vault_root_token.stdout

- name: Unseal Vault
  shell:
    cmd: "vault operator unseal --format json {{ vault_init_json.unseal_keys_hex[0] }}"
  register: vault_unseal_raw
  no_log: true
  when:
    - vault_status_json is defined
    - vault_status_json.sealed
  changed_when: false
  failed_when: vault_unseal_raw.rc == 1

# - set_fact:
#     vault_unseal_json: "{{ vault_unseal_raw.stdout | from_json }}"
#   when:
#     - vault_unseal_raw is defined
#     - vault_unseal_raw.stdout is defined
#     - vault_unseal_raw.rc == 0

# - debug:
#     var: vault_unseal_json
#   when: vault_unseal_raw is defined and vault_unseal_raw.stdout is defined

- set_fact:
    vault_root_token: "{{ vault_init_json.root_token }}"
  no_log: true
  when:
    - vault_init_json is defined
    - vault_init_json.root_token is defined

- name: Login with root token
  shell:
    cmd: vault login --format json {{ vault_root_token }}
  no_log: true
  register: vault_login_raw
  changed_when: false
  failed_when: vault_login_raw.rc != 0

# - set_fact:
#     vault_login_json: "{{ vault_login_raw.stdout | from_json }}"
#   when:
#     - vault_login_raw is defined
#     - vault_login_raw.stdout is defined
#     - vault_login_raw.rc == 0

# - debug:
#     var: vault_login_json
#   when: vault_login_raw is defined and vault_login_raw.stdout is defined

- name: Check Vault post-login status
  command: vault status -format=json
  register: vault_post_status_raw
  changed_when: false
  failed_when: vault_post_status_raw.rc == 1

- set_fact:
    vault_post_status_json: "{{ vault_post_status_raw.stdout | from_json }}"
  when: vault_post_status_raw.stdout is defined

- name: Vault post-login status
  debug:
    var: vault_post_status_json
  when: vault_post_status_json is defined

# See terraform/vault for resources
# Note that Terraform must be installed on Ansible host

- set_fact:
    vault_terraform_dir: "{{ lookup('pipe', 'git rev-parse --show-toplevel') }}/terraform/vault"

- set_fact:
    vault_terraform_cert_dir: "{{ lookup('pipe', 'git rev-parse --show-toplevel') }}/certs"

- name: Copy Vault CA cert to Ansible host
  fetch:
    src: "{{ vault_ca_cert_dir }}/ca.crt"
    dest: "{{ vault_terraform_cert_dir }}/vault-ca.crt"
    flat: true

# Clear any existing state from previous Vault server or Molecule testing. THIS CAN
# DELETE IMPORTANT DATA! Take care when running tests when a state file already exists.

- name: Delete existing state from Terraform if any
  become: false
  community.general.terraform:
    project_path: "{{ vault_terraform_dir }}"
    workspace: "{{ vault_terraform_workspace }}"
    state: absent
    variables:
      vault_token: "{{ vault_root_token }}"
      vault_address: "https://{{ ansible_default_ipv4.address }}:8200"
      vault_ca_cert_file: "{{ vault_terraform_cert_dir }}/vault-ca.crt"
  delegate_to: localhost

- name: Provision Vault secrets with Terraform provider
  become: false
  community.general.terraform:
    project_path: "{{ vault_terraform_dir }}"
    workspace: "{{ vault_terraform_workspace }}"
    state: present
    force_init: true
    check_destroy: true
    variables:
      vault_token: "{{ vault_root_token }}"
      vault_address: "https://{{ ansible_default_ipv4.address }}:8200"
      vault_ca_cert_file: "{{ vault_terraform_cert_dir }}/vault-ca.crt"
      vault_audit_path: "{{ vault_log_file }}"
      admin_password: "{{ vault_admin_password }}"
  register: vault_terraform_output
  no_log: true
  delegate_to: localhost

- debug:
    msg: "{{ vault_terraform_output.stdout }}"
  when: vault_terraform_output is defined
