---
- name: Create Vault directories
  file:
    path: "{{ item }}"
    mode: 0755
    owner: vault
    group: vault
    state: directory
  with_items:
    - "{{ vault_config_dir }}"
    - "{{ vault_data_dir }}/raft"
    - "{{ vault_tls_dir }}"
    - "{{ vault_ca_cert_dir }}"
    - "{{ vault_policy_dir }}"

- name: Copy service file
  copy:
    src: "vault.service"
    dest: "/etc/systemd/system/vault.service"
    mode: 0644
    owner: root
    group: root
  notify:
    - reload vault

- name: Copy Vault config files
  template:
    src: "vault.hcl.j2"
    dest: "{{ vault_config_dir }}/vault.hcl"
    mode: 0644
    owner: vault
    group: vault
  notify:
    - reload vault

- name: Start Vault
  systemd:
    name: vault
    state: started
    enabled: true
  register: vault_started

- name: Wait for Vault port
  wait_for:
    port: 8200
    state: started

- name: Vault Initialization
  import_tasks: init.yml

# Setup CA, file audit, cert auth, admin role
- name: Root token setup
  import_tasks: root.yml
