---
- name: Create Vault restricted directories
  file:
    path: "{{ item }}"
    mode: 0700
    owner: vault
    group: vault
    state: directory
  with_items:
    - "{{ vault_data_dir }}"
    - "{{ vault_data_dir }}/raft"
    - "{{ vault_log_dir }}"
    - "{{ vault_tls_dir }}"

- name: Create Vault config directories
  file:
    path: "{{ item }}"
    mode: 0755
    owner: vault
    group: vault
    state: directory
  with_items:
    - "{{ vault_config_dir }}"
    - "{{ vault_ca_cert_dir }}"

- name: Remove default TLS cert and key
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ vault_tls_dir }}/tls.key"
    - "{{ vault_tls_dir }}/tls.crt"

- import_tasks: server.yml
  when: >
    'server' in group_names or
    'mol_server' in group_names

- import_tasks: agent.yml
  when: >
    ('client' in group_names or 'mol_client' in group_names) or
    (('server' in group_names or 'mol_server in group_names') and vault_setup_agent)
