---
# TODO replace with Vault Terraform provider
# Enable PKI secrets engine
# Create Root CA, Intermediate CA in Vault
# Create Vault role for deploying certificates
- name: Create personal CA in Vault
  script: "../files/vault_ca.sh"

- name: Create Vault log file
  file:
    path: "{{ vault_log_file }}"
    mode: 0640
    owner: vault
    group: vault
    state: touch

- name: Enable file audit
  command: "vault audit enable file file_path={{ vault_log_file }}"

- name: Set up logrotate for file audit
  template:
    src: "logrotate-vault.j2"
    dest: "/etc/logrotate.d/vault"
    mode: 0644
    owner: root
    group: root

- name: Enable cert auth
  command: "vault auth enable cert"

- name: Enable kv secrets engine
  command: "vault secrets enable -path=kv kv-v2"

- name: Read admin policy
  copy:
    src: "admin_policy.hcl"
    dest: "{{ vault_policy_dir }}/admin.hcl"
    mode: 0640
    owner: vault
    group: vault

- name: Create admin policy
  command: "vault policy write admin {{ vault_policy_dir }}/admin.hcl"
  register: create_admin_policy
  failed_when: create_admin_policy.rc != 0

- name: Setup admin role
  script: "../files/admin_auth_role.sh"

# - name: Revoke root token (Optional)
#   when: vault_revoke_root_token|bool
