---
- name: Create Nomad directories
  file:
    path: "{{ item }}"
    mode: 0755
    owner: nomad
    group: nomad
    state: directory
  with_items:
    - "{{ nomad_config_dir }}"
    - "{{ nomad_data_dir }}"

- name: Create Nomad TLS directory
  file:
    path: "{{ nomad_tls_dir }}"
    mode: 0700
    owner: nomad
    group: nomad
    state: directory

- name: Install CNI plugins
  import_tasks: cni_plugins.yml
  when: "'server' not in group_names"

- name: Setup Nomad Gossip Encryption
  import_tasks: gossip.yml
  when: "'server' in group_names"

- name: Setup Nomad TLS
  import_tasks: tls.yml

- name: Setup Vault integration
  import_tasks: vault_integration.yml
  when: "'server' in group_names and setup_vault_integration"

- name: Copy service file
  template:
    src: "nomad.service.j2"
    dest: "/etc/systemd/system/nomad.service"
    mode: 0644
    owner: root
    group: root
  notify:
    - restart nomad

- name: Copy Nomad config files
  block:
    - name: Common config
      template:
        src: "nomad.hcl.j2"
        dest: "{{ nomad_config_dir }}/nomad.hcl"
        mode: 0644
        owner: nomad
        group: nomad

    - name: Server-only config
      template:
        src: "server.hcl.j2"
        dest: "{{ nomad_config_dir }}/server.hcl"
        mode: 0644
        owner: nomad
        group: nomad
      when: "'server' in group_names"

    - name: Client-only config
      template:
        src: "client.hcl.j2"
        dest: "{{ nomad_config_dir }}/client.hcl"
        mode: 0644
        owner: nomad
        group: nomad
      when: "'server' not in group_names"
  notify:
    - reload nomad

- name: Start Nomad
  systemd:
    name: nomad
    state: started
    enabled: true
    daemon_reload: true
  register: nomad_started

# Apply all service and config changes
- name: Restart Nomad if there are changes
  meta: flush_handlers

- name: Wait for Nomad port
  wait_for:
    port: 4646
    state: started
