---
- name: Add TLS template stanza to consul-template
  blockinfile:
    path: "{{ consul_template_config }}"
    marker: "# {mark} Nomad TLS"
    backup: true
    validate: consul-template -config=%s -parse-only
    block: |
      template {
        contents = <<EOF
      {{ '{{' }} with secret "pki_int/issue/cluster" "common_name=server.global.nomad" "ttl=24h" "alt_names=localhost" "ip_sans={{ nomad_ip_sans }}" {{ '}}' }}
      {{ '{{' }} .Data.certificate {{ '}}' }}
      {{ '{{' }} end {{ '}}' }}
      EOF
        destination = "{{ nomad_tls_dir }}/cert.crt"
        perms = 0600
        user = "nomad"
        group = "nomad"
        command = "date && if systemctl is-active nomad; then service nomad reload; fi"
      }

      template {
        contents = <<EOF
      {{ '{{' }} with secret "pki_int/issue/cluster" "common_name=server.global.nomad" "ttl=24h" "alt_names=localhost" "ip_sans={{ nomad_ip_sans }}" {{ '}}' }}
      {{ '{{' }} .Data.private_key {{ '}}' }}
      {{ '{{' }} end {{ '}}' }}
      EOF
        destination = "{{ nomad_tls_dir }}/key.pem"
        perms = 0400
        user = "nomad"
        group = "nomad"
        command = "date && if systemctl is-active nomad; then service nomad reload; fi"
      }

      template {
        contents = <<EOF
      {% raw %}{{ with secret "pki_int/issue/cluster" "common_name=server.global.nomad" "ttl=24h" }}
      {{ .Data.issuing_ca }}
      {{ end }}
      {% endraw %}
      EOF
        destination = "{{ nomad_tls_dir }}/ca.crt"
        perms = 0640
        user = "nomad"
        group = "debian"
        command = "date && if systemctl is-active nomad; then service nomad reload; fi"
      }
  notify: reload consul-template

# TODO
- name: Set environment variables
  lineinfile:
    path: "/etc/environment"
    line: "{{ item }}"
  with_items:
    - "NOMAD_ADDR=https://{{ ansible_default_ipv4.address }}:4646"
    - "NOMAD_CACERT={{ nomad_tls_dir }}/ca.crt"
