---
coredns_version: 1.10.1
coredns_arch_map:
  x86_64: amd64
  armv7l: arm
coredns_arch: "{{ coredns_arch_map[ansible_architecture] }}"
coredns_tar: coredns_{{ coredns_version }}_{{ ansible_system|lower }}_{{ coredns_arch }}.tgz

coredns_dns_port: 5300
coredns_user: coredns
coredns_group: coredns
