---
- name: Install docker module
  pip:
    name: docker
    state: present

- name: Create proxy docker network
  community.docker.docker_network:
    name: proxy

- name: Create socket-proxy docker network
  community.docker.docker_network:
    name: socket-proxy

# WARNING: this overwrites existing config and data if already exists
# - name: Clone compose-stacks repo
#   git:
#     repo: "{{ stacks_repo_url }}"
#     dest: "{{ stacks_directory }}"
#     version: "{{ stacks_version }}"
#   when: clone_repo

- name: Create .env file
  copy:
    src: "{{ stacks_directory }}/.env.example"
    dest: "{{ stacks_directory }}/.env"
    remote_src: true
    force: false  # do not overwrite if exist
  register: env_file

# dependence on .env in compose-stacks
- name: Populate environment variables
  lineinfile:
    path: "{{ stacks_directory }}/.env"
    regexp: "^{{ item.key }}"
    line: "{{ item.key }}{{ item.value }}"
    state: present
  with_items:
    - { key: "DOMAIN_NAME=", value: "{{ domain_name }}" }
    - { key: "CA_EMAIL=", value: "{{ ca_email }}" }
  when: env_file.changed

- name: Start all compose services
  command:
    cmd: "./bin/start-all"
    chdir: "{{ stacks_directory }}"
  when: first_time_setup == false
