---
- name: Install docker module
  pip:
    name: docker
    state: present

- name: Create docker networks
  community.docker.docker_network:
    name: "{{ item }}"
  with_items:
    - "{{ proxy_network }}"
    - "{{ socket_proxy_network }}"

# WARNING: this overwrites existing config and data if already exists
- name: Clone compose-stacks repo
  git:
    repo: "{{ stacks_repo_url }}"
    dest: "{{ docker_destination }}"
    version: "{{ stacks_version }}"
  when: clone_repo

- name: Create .env file
  copy:
    src: "{{ docker_destination }}/.env.example"
    dest: "{{ docker_destination }}/.env"
    remote_src: true
    force: false  # do not overwrite if exist
  register: env_file

# dependence on .env in compose-stacks
- name: Populate environment variables
  lineinfile:
    path: "{{ docker_destination }}/.env"
    regexp: "^{{ item.key }}"
    line: "{{ item.key }}{{ item.value }}"
    state: present
  with_items:
    - { key: "DOMAIN_NAME=", value: "{{ domain_name }}" }
    - { key: "CA_EMAIL=", value: "{{ ca_email }}" }
  when: env_file.changed

- name: Start compose stacks
  command:
    cmd: "make up c={{ item }}"
    chdir: "{{ docker_destination }}"
  with_items:
    - "{{ stacks }}"
