---
- name: Get $USER
  command:
    cmd: "echo $USER"
  register: user
  changed_when: false

- name: Create acme directory
  file:
    path: "{{ stacks_directory }}/traefik/acme"
    state: directory

- name: Create acme.json
  file:
    path: "{{ stacks_directory }}/traefik/acme/acme.json"
    state: touch
    owner: "{{ user.stdout }}"
    group: "{{ user.stdout }}"
    mode: '0600'
    modification_time: preserve
    access_time: preserve

- name: Uncomment certresolver in Traefik docker-compose.yml

- name: Start Traefik to get SSL certificates
  command:
    cmd: "make recreate c=traefik"
    chdir: "{{ stacks_directory }}"

- name: Check acme.json
