apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://172.19.0.2:9090
    jsonData:
      timeInterval: 10s
    version: 1
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: http://172.19.0.4:3100
    jsonData:
      maxLines: 1000
