---
- name: Get checksum
  set_fact:
    coredns_checksum: "{{ lookup('url', coredns_checksum_url).split(' ')[0] }}"
  run_once: true

- name: Download coredns
  get_url:
    url: "{{ coredns_url }}"
    dest: "/tmp/coredns-{{ coredns_version }}.tgz"
    checksum: "sha256:{{ coredns_checksum }}"

- name: Install coredns
  unarchive:
    src: "/tmp/coredns-{{ coredns_version }}.tgz"
    dest: /usr/local/bin
    remote_src: true
    creates: /usr/local/bin/coredns
    owner: root
    group: root
    mode: 0755

- name: Create coredns directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - /etc/coredns
    - /etc/coredns/keys
    - /etc/coredns/zones

- name: Copy coredns.service file
  template:
    src: coredns.service.j2
    dest: /etc/systemd/system/coredns.service
    owner: root
    group: root
    mode: 0644
  notify: restart coredns

- name: Copy configuration file
  template:
    src: Corefile.j2
    dest: /etc/coredns/Corefile
    owner: root
    group: root
    mode: 0644
  notify: restart coredns

# - name: Copy key files
#   template:
#     src: keys.j2
#     dest: /etc/coredns/keys
#     owner: coredns
#     group: coredns
#     mode: 0400

- name: Copy zone files
  template:
    src: zone.j2
    dest: /etc/coredns/zones/kencv.xyz
    owner: root
    group: root
    mode: 0644

- name: Start and enable coredns
  systemd:
    name: coredns
    state: started
    enabled: true
    daemon_reload: true

- wait_for:
    port: "{{ coredns_dns_port }}"
