---
- hosts: client
  become: true
  vars:
    - server_ip: "10.10.10.110"
    - nfs_ip: "10.10.10.102"
    - nfs_share_mounts:
        - src: "{{ nfs_ip }}:/home/debian/apps/test-apps"
          path: "/mnt/storage"
          state: mounted

  tasks:
    - name: Configure and start Consul
      import_playbook: playbook/consul.yml
      vars:
        server: false
        start_cluster: true
        consul_server_ip: "{{ server_ip }}"
        gossip_encryption_key: ""

    - name: Configure and start Nomad
      import_playbook: playbook/nomad.yml
      vars:
        server: false
        start_cluster: true
        nomad_server_ip: "{{ server_ip }}"

    - name: Mount NFS shares
      become: true
      import_role:
        name: kencx.ansible.nfs

    - name: Goss smoke test
      import_role:
        name: kencx.ansible.goss
      vars:
        - goss_dir: "./playbooks/templates/goss"
        - goss_file: "client.yml"
