---
- hosts: client
  become: true
  vars:
    cluster_server_ip: "10.10.10.110"

  pre_tasks:
    # TODO too dependent on server.yml playbook
    - name:
      file:
        path: "/usr/share/ca-certificates/vault"
        state: directory
        owner: vault
        group: vault
        mode: 0640
    - name: Copy certificate-chain to remote host
      copy:
        src: "/tmp/certs/vault.crt"
        dest: "/usr/share/ca-certificates/vault/vault.crt"
        mode: "0640"
        owner: "vault"
        group: "vault"
    - name: Add certificate-chain to remote ca-certificates.conf
      lineinfile:
        path: "/etc/ca-certificates.conf"
        line: "vault/vault.crt"
    - name: Update remote trust store
      command: update-ca-certificates
      register: update_cert_output
      changed_when: '"1 added" in update_cert_output.stdout'

    - name: Vault status check
      command: "vault status"
      environment:
        VAULT_ADDR: "https://{{ cluster_server_ip }}:8200"
      changed_when: false

    - name: Vault login
      block:
        - name: Get root token from Bitwarden
          script: "./roles/vault/files/bw_get.sh 'Vault Root Token' {{ bw_password }}"
          register: vault_root_token_raw

        - set_fact:
            vault_root_token_json: "{{ vault_root_token_raw.stdout | from_json }}"

        - name: Login
          shell:
            cmd: "vault login --format json {{ vault_root_token_json.data.data }}"
          environment:
            VAULT_ADDR: "https://{{ cluster_server_ip }}:8200"
          register: vault_login_operation
          when:
            - vault_root_token_json is defined
            - vault_root_token_json.data.data is defined
            - vault_root_token_json.success
          changed_when: false
          failed_when: vault_login_operation.rc == 1

  roles:
    - name: Mount NFS shares
      role: kencx.ansible.nfs
    - role: consul-template
    - role: consul
    - role: nomad

  tasks:
    - name: Register Nomad client as Consul service
      import_tasks: nomad_consul_register.yml

    - name: Goss smoke test
      import_role:
        name: kencx.ansible.goss
      vars:
        - goss_dir: "./goss"
        - goss_file: "client.yml"
