---
- hosts: client
  become: true
  vars:
    nfs_ip: "10.10.10.102"
    nfs_share_mounts:
      - src: "{{ nfs_ip }}:/home/debian/apps/test-apps"
        path: "/mnt/storage"
        state: mounted
      - src: "{{ nfs_ip }}:/home/debian/apps/tls"
        path: "{{ consul_template_dir }}/tls"
        state: mounted
    server_address: "10.10.10.130"
    client_address: "{{ ansible_default_ipv4.address }}"
    consul_template_dir: "/opt/consul-template"
    nomad_config_dir: "/etc/nomad.d"
    nomad_tls_dir: "/opt/nomad/data/tls"

  pre_tasks:
    # TODO too dependent on server.yml playbook
    - name:
      file:
        path: "/usr/share/ca-certificates/vault"
        state: directory
        owner: vault
        group: vault
        mode: 0640
    - name: Copy certificate-chain to remote host
      copy:
        src: "/tmp/certs/vault.crt"
        dest: "/usr/share/ca-certificates/vault/vault.crt"
        mode: "0640"
        owner: "vault"
        group: "vault"
    - name: Add certificate-chain to remote ca-certificates.conf
      lineinfile:
        path: "/etc/ca-certificates.conf"
        line: "vault/vault.crt"
    - name: Update remote trust store
      command: update-ca-certificates
      register: update_cert_output
      changed_when: '"1 added" in update_cert_output.stdout'

    - name: Vault status check
      shell:
        cmd: "VAULT_ADDR=https://{{ server_address }}:8200 vault status"
      changed_when: false

  roles:
    - name: Mount NFS shares
      role: kencx.ansible.nfs

    - role: consul-template
      vars:
        vault_address: "{{ server_address }}"

    - role: consul
      vars:
        consul_server_ip: "{{ server_address }}"
        consul_common_name: "client.dc1.consul"
        consul_ip_sans: "127.0.0.1,{{ client_address }}"

    - role: nomad
      vars:
        nomad_server_ip: "{{ server_address }}"
        nomad_common_name: "client.global.nomad"
        nomad_ip_sans: "127.0.0.1,{{ client_address }}"

  tasks:
    - name: Register Nomad client as Consul service
      import_tasks: nomad_consul_register.yml

    - name: Goss smoke test
      import_role:
        name: kencx.ansible.goss
      vars:
        - goss_dir: "./goss"
        - goss_file: "client.yml"
