---
- hosts: server, !dev
  become: true
  tags: server
  roles:
    - name: Create root, intermediate CA for Vault
      role: kencx.ansible.ssl
      become: true
      run_once: true

    - role: vault
    - role: consul-template
    - role: consul
    - role: nomad

  tasks:
    - name: Goss smoke test
      import_role:
        name: kencx.ansible.goss
      vars:
        goss_dir: "./goss"
        goss_file: "server.yml"

- hosts: client, !dev
  become: true
  tags: client
  roles:
    - name: Mount NFS shares on client
      role: kencx.ansible.nfs
      tags: nfs

    - role: vault
    - role: consul-template
    - role: consul
    - role: nomad

  tasks:
    - name: Goss smoke test
      import_role:
        name: kencx.ansible.goss
      vars:
        goss_dir: "./goss"
        goss_file: "client.yml"
