---
- hosts: server
  become: true
  vars:
    nfs_ip: "10.10.10.102"
    nfs_share_mounts:
      - src: "{{ nfs_ip }}:/home/debian/apps/tls"
        path: "{{ consul_template_dir }}/tls"
        state: mounted

    cluster_server_ip: "{{ ansible_default_ipv4.address }}"

    vault_config_dir: "/etc/vault.d"
    vault_tls_dir: "/opt/vault/tls"
    vault_ca_cert_dir: "/usr/share/ca-certificates/vault"
    consul_template_dir: "/opt/consul-template"

    nomad_config_dir: "/etc/nomad.d"
    nomad_tls_dir: "/opt/nomad/data/tls"

  roles:
    # requires localhost root
    # NOTE: /tmp/certs must already exist with 1000:1000
    # NOTE: /tmp/certs/vault.crt ca-chain must already exist with 1000:1000
    - name: Setup Vault TLS certificates
      role: kencx.ansible.ssl
      vars:
        ssl_create_root_ca: false
        ssl_create_intermediate_ca: false
        ssl_create_cert_chain: false
        ssl_remote_user: "vault"
        ssl_remote_tls_dir: "{{ vault_tls_dir }}"
        ssl_remote_ca_trust_store_dir: "{{ vault_ca_cert_dir }}"
        ssl_ca_chain_name: "vault"
        ssl_remote_cert_name: "vault"
        ssl_remote_cert_common_name: "vault"
        ssl_remote_cert_subject_alt_name: "IP:{{ cluster_server_ip }}"
        ssl_remote_cert_ttl: "+365d"

    - name: Mount NFS shares
      role: kencx.ansible.nfs

    - role: vault

    - role: consul-template
      vars:
        vault_address: "{{ cluster_server_ip }}"

    - role: consul
      vars:
        consul_vault_addr: "https://{{ cluster_server_ip }}:8200"
        consul_common_name: "server.dc1.consul"
        consul_ip_sans: "127.0.0.1,{{ cluster_server_ip }}"

    - role: nomad
      vars:
        nomad_vault_addr: "https://{{ cluster_server_ip }}:8200"
        nomad_common_name: "server.global.nomad"
        nomad_ip_sans: "127.0.0.1,{{ cluster_server_ip }}"

  tasks:
    - name: Register Vault as Consul service
      import_tasks: vault_consul_register.yml

    - name: Register Nomad as Consul service
      import_tasks: nomad_consul_register.yml

    # - name: Sign out of Vault root
    #   file:
    #     path: /root/.vault-token
    #     state: absent

    - name: Goss smoke test
      import_role:
        name: kencx.ansible.goss
      vars:
        - goss_dir: "./goss"
        - goss_file: "server.yml"
