---
- hosts: server
  become: true

  roles:
    - name: Configure Vault
      role: vault

    - name: Install consul-template
      role: consul-template

    - name: Configure Consul
      role: consul

    - name: Configure Nomad
      role: nomad

  tasks:
    - name: Restart Vault
      systemd:
        name: vault
        state: reloaded

    - name: Goss smoke test
      import_role:
        name: kencx.ansible.goss
      vars:
        - goss_dir: "./goss"
        - goss_file: "server.yml"
