---
- hosts: "{{ host | default(omit) }}"
  become: true
  vars:
    reset_cluster_data: false

  tasks:
    - name: Configure and start Consul
      import_playbook: playbook/consul.yml
      vars:
        server: true
        start_cluster: true
        gossip_encryption_key: ""

    - name: Configure and start Nomad
      import_playbook: playbook/nomad.yml
      vars:
        server: true
        start_cluster: true

    - name: Goss smoke test
      import_role:
        name: kencx.ansible.goss
      vars:
        - goss_dir: "./playbooks/templates/goss"
        - goss_file: "server.yml"

    # WARNING! This clears all cluster node data.
    # This is only necessary when templating the server with Packer
    # Do not run this with Terraform
    - name: Reset cluster
      when: reset_cluster_data|bool
      block:
        - name: Stop Nomad, Consul
          systemd:
            name: "{{ item }}"
            state: stopped
            enabled: true
          with_items:
            - nomad
            - consul

        - name: Delete Nomad, Consul data directories
          file:
            path: "{{ item }}"
            state: absent
          with_items:
            - "{{ nomad_data_dir }}"
            - "{{ consul_data_dir }}"

        - name: Create Nomad directories
          file:
            path: "{{ nomad_data_dir }}"
            mode: 0755
            owner: nomad
            group: nomad
            state: directory

        - name: Create Consul directories
          file:
            path: "{{ consul_data_dir }}"
            mode: 0755
            owner: consul
            group: consul
            state: directory
