---
- hosts: server
  become: true
  vars:
    server_address: "{{ ansible_default_ipv4.address }}"
    vault_tls_dir: "/opt/vault/tls"
    vault_ca_cert_dir: "/usr/share/ca-certificates/vault"

  roles:
    # requires localhost root
    - name: Setup Vault TLS certificates
      role: kencx.ansible.ssl
      vars:
        ssl_create_root_ca: false
        ssl_create_intermediate_ca: false
        ssl_create_cert_chain: false
        ssl_remote_user: "vault"
        ssl_remote_tls_dir: "{{ vault_tls_dir }}"
        ssl_remote_ca_trust_store_dir: "{{ vault_ca_cert_dir }}"
        ssl_ca_chain_name: "vault"
        ssl_remote_cert_name: "vault"
        ssl_remote_cert_common_name: "vault"
        ssl_remote_cert_subject_alt_name: "IP:{{ server_address }}"
        ssl_remote_cert_ttl: "+365d"

    - role: vault
    - role: consul-template
      vars:
        vault_address: "{{ server_address }}"

    - role: consul
      vars:
        consul_ip_sans: "127.0.0.1,{{ server_address }}"
    - role: nomad
      vars:
        nomad_ip_sans: "127.0.0.1,{{ server_address }}"

  tasks:
    - name: Restart Vault
      systemd:
        name: vault
        state: reloaded

    - name: Goss smoke test
      import_role:
        name: kencx.ansible.goss
      vars:
        - goss_dir: "./goss"
        - goss_file: "server.yml"
