---
- hosts: server
  become: true
  roles:
    # requires localhost root
    # NOTE: /tmp/certs must already exist with 1000:1000
    # NOTE: /tmp/certs/vault.crt ca-chain must already exist with 1000:1000
    - name: Setup Vault TLS certificates
      role: kencx.ansible.ssl
      vars:
        ssl_create_root_ca: false
        ssl_create_intermediate_ca: false
        ssl_create_cert_chain: false
        ssl_remote_user: "vault"
        ssl_remote_tls_dir: "{{ vault_tls_dir }}"
        ssl_remote_ca_trust_store_dir: "{{ vault_ca_cert_dir }}"
        ssl_ca_chain_name: "vault"
        ssl_remote_cert_name: "vault"
        ssl_remote_cert_common_name: "vault"
        ssl_remote_cert_subject_alt_name: "IP:{{ cluster_server_ip }},DNS:vault.service.consul"
        ssl_remote_cert_ttl: "+365d"

    - name: Mount NFS shares
      role: kencx.ansible.nfs
    - role: vault
    - role: consul-template
    - role: consul
    - role: nomad

  tasks:
    - name: Register Vault as Consul service
      import_tasks: vault_consul_register.yml

    - name: Register Nomad as Consul service
      import_tasks: nomad_consul_register.yml

    # - name: Sign out of Vault root
    #   file:
    #     path: /root/.vault-token
    #     state: absent

    - name: Goss smoke test
      import_role:
        name: kencx.ansible.goss
      vars:
        - goss_dir: "./goss"
        - goss_file: "server.yml"
