---
- hosts: server
  become: true
  vars:
    vault_tls_dir: "/opt/vault/tls"
    vault_certificate_dir: "/usr/share/ca-certificates/vault"

  roles:
    # requires localhost root
    - name: Setup Vault TLS certificates
      role: kencx.ansible.ssl
      vars:
        ssl_remote_user: "vault"
        ssl_remote_tls_dir: "{{ vault_tls_dir }}"
        ssl_remote_trust_store_dir: "{{ vault_certificate_dir }}"
        ssl_remote_cert_name: "vault"
        ssl_remote_cert_common_name: "vault"
        ssl_remote_cert_subject_alt_name: ""
        ssl_remote_cert_ttl: "+365d"

    - name: Configure Vault
      role: vault

    - name: Install consul-template
      role: consul-template

    - name: Configure Consul
      role: consul

    - name: Configure Nomad
      role: nomad

  tasks:
    - name: Restart Vault
      systemd:
        name: vault
        state: reloaded

    - name: Goss smoke test
      import_role:
        name: kencx.ansible.goss
      vars:
        - goss_dir: "./goss"
        - goss_file: "server.yml"
