---
- hosts: all
  tasks:
    - name: Create Nomad directories
      become: true
      file:
        path: "{{ item }}"
        mode: 0755
        owner: nomad
        group: nomad
        state: directory
      with_items:
        - "/opt/nomad/data"
        - "/etc/nomad.d"

    - name: Create Consul directories
      become: true
      file:
        path: "{{ item }}"
        mode: 0755
        owner: consul
        group: consul
        state: directory
      with_items:
        - "/opt/consul"
        - "/etc/consul.d"

    - name: Copy service file
      become: true
      copy:
        src: "./templates/server/{{ item }}"
        dest: "/etc/systemd/system/{{ item }}"
        owner: root
        group: root
      with_items:
        - "nomad.service"
        - "consul.service"
      notify:
        - reload nomad
        - reload consul

    - name: Copy Nomad config files
      become: true
      template:
        src: "./templates/server/nomad.hcl.j2"
        dest: "/etc/nomad.d/nomad.hcl"
        owner: nomad
        group: nomad
        mode: 0644
      vars:
        - bootstrap_expect: 1
      notify:
        - reload nomad

    - name: Copy Consul config files
      become: true
      template:
        src: "./templates/server/consul.hcl.j2"
        dest: "/etc/consul.d/consul.hcl"
        owner: consul
        group: consul
        mode: 0644
      notify:
        - reload consul

    - name: Start nomad
      become: true
      systemd:
        name: nomad
        state: started
        enabled: true
        daemon_reload: true
      register: nomad_started

    - name: Start consul
      become: true
      systemd:
        name: consul
        state: started
        enabled: true
        daemon_reload: true
      register: consul_started

    - name: Nomad port open
      wait_for:
        port: 4646
        delay: 5

  handlers:
    - name: reload nomad
      systemd:
        name: nomad
        state: reloaded
      when: not nomad_started.changed

    - name: reload consul
      systemd:
        name: consul
        state: reloaded
      when: not consul_started.changed
