---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: instance
    box: "kenc/debian-11.5-v2"
    box_url: "file://../../packer/vagrant/builds/base.libvirt.2022-11-29.box"
    config_options:
      ssh.username: "debian"
      ssh.insert_key: false
      ssh.private_key_path: "~/.ssh/vagrant"
      synced_folder: false

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../roles"
verifier:
  name: ansible
