---
- name: Verify
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Include default vars
      include_vars:
        dir: "{{ role_directory }}/defaults/"
        extensions:
          - 'yml'
          - 'yaml'
      vars:
        role_directory: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/roles/{{ lookup('env', 'MOLECULE_SCENARIO_NAME') }}"

    - name: User created
      getent:
        database: passwd
        key: "{{ common_user }}"

    - name: Packages installed
      apt:
        name: "{{ item }}"
        state: present
      with_items: "{{ common_packages }}"

    - name: Hashicorp tools installed
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - nomad
        - consul
        - vault
        - consul-template

    - name: Nomad stopped
      systemd:
        name: nomad
        state: stopped

    - name: Bitwarden installed
      stat:
        path: "/usr/bin/bw"
      register: bw
      changed_when: false
      failed_when: bw.stat.exists != true

    - name: NFS share directories created
      file:
        path: "{{ common_nfs_dir }}"
        mode: 0755
        owner: "{{ common_user }}"
        group: "{{ common_user }}"
        state: directory
