---
- name: Check autorestic exists
  stat:
    path: "{{ autorestic_bin_dir }}/autorestic"
  register: autorestic_path

- name: Check autorestic version
  shell: autorestic --version | awk '{print $3}'
  register: autorestic_installed_version
  changed_when: false
  when: autorestic_path.stat.exists

# TODO
# - name: Install autorestic
#   when: autorestic_installed_version.stdout is version(autorestic_version, '<')
#   block:
#     - name: Download autorestic
#       ansible.builtin.get_url:
#         url: ""
#         dest: ""
#         checksum: ""
#         mode: 0644
#
#     - name: Extract autorestic
#       ansible.builtin.command:
#         chdir: ""
#         cmd: "bzip2 -d"
#
#     - name: Copy autorestic binary to install directory
#       ansible.builtin.copy:
#         src: ""
#         dest: "{{ autorestic_bin_dir }}"
#         mode: 0755
