---
- name: "Install Goss binary"
  get_url:
    url: "{{ goss_url }}"
    dest: "{{ goss_dest }}"
    mode: "0755"

- name: Copy Goss file
  become: true
  template:
    src: "{{ goss_file_template }}"
    dest: "{{ goss_file_dest }}"
    mode: "0755"

- name: "Goss Validate"
  command: "goss -g {{ goss_file_dest }} validate"
  changed_when: false
