---
- name: Generate random password
  set_fact:
    random_password: "{{ lookup('password', '/dev/null') }}"

- name: Generate temp SSH key pair
  community.crypto.openssh_keypair:
    path: "/tmp/temp_ssh_key"
    regenerate: always
    type: "ed25519"
    state: present
  register: temp_ssh_key
  delegate_to: localhost

- debug:
    var: "proxmox_api_token_id"
- debug:
    var: "proxmox_api_token_secret"

- fail:
    msg: "fail"

- name: Create temp LXC
  proxmox:
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    # api_token_id: "{{ proxmox_api_token_id }}"
    # api_token_secret: "{{ proxmox_api_token_secret }}"
    storage: "{{ proxmox_storage }}"

    node: "{{ proxmox_node }}"
    vmid: "{{ temp_vmid }}"
    hostname: "{{ temp_hostname }}"
    ostemplate: "local:vztmpl/{{ base_image }}"
    unprivileged: true

    cores: 1
    memory: 4096
    swap: 2048
    disk: "{{ temp_disk_size }}"

    netif: '{"net0":"name=eth0,ip={{ temp_ip_address }},gw={{ temp_gateway }},bridge=vmbr1"}'
    password: "{{ random_password }}"
    pubkey: "{{ temp_ssh_key.public_key }}"
    state: present
