---
- name: Start temp LXC
  proxmox:
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    # api_token_id: "{{ proxmox_api_token_id }}"
    # api_token_secret: "{{ proxmox_api_token_secret }}"
    vmid: "{{ temp_vmid }}"
    state: started
